encoding: utf-8
name: Your New Jekyll Site
markdown: kramdown
highlighter: pygments
baseurl: /
url: /
gems: [jekyll-paginate]
permalink: date
relative_permalinks: false
paginate: 6
paginate_path: "/blogindex/page:num/"

